// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FBProtocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_CHAT_PACKET : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SC_CHAT_PACKET GetRootAsSC_CHAT_PACKET(ByteBuffer _bb) { return GetRootAsSC_CHAT_PACKET(_bb, new SC_CHAT_PACKET()); }
  public static SC_CHAT_PACKET GetRootAsSC_CHAT_PACKET(ByteBuffer _bb, SC_CHAT_PACKET obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_CHAT_PACKET __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int SenderId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<FBProtocol.SC_CHAT_PACKET> CreateSC_CHAT_PACKET(FlatBufferBuilder builder,
      int sender_id = 0,
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    SC_CHAT_PACKET.AddMessage(builder, messageOffset);
    SC_CHAT_PACKET.AddSenderId(builder, sender_id);
    return SC_CHAT_PACKET.EndSC_CHAT_PACKET(builder);
  }

  public static void StartSC_CHAT_PACKET(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSenderId(FlatBufferBuilder builder, int senderId) { builder.AddInt(0, senderId, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(1, messageOffset.Value, 0); }
  public static Offset<FBProtocol.SC_CHAT_PACKET> EndSC_CHAT_PACKET(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FBProtocol.SC_CHAT_PACKET>(o);
  }
}


static public class SC_CHAT_PACKETVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SenderId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Message*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
